"""fix migrations

Revision ID: 683006a25d4a
Revises: 
Create Date: 2023-04-14 17:00:45.304219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683006a25d4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
